export const songsDB = [
  {
    songId: 1,
    title: "Homeworld Collapse",
    artist: "Arthur Vyncke",
    image: "https://www.free-stock-music.com/thumbnails/arthur-vyncke-homeworld-collapse.jpg",
    path: "https://www.free-stock-music.com/music/arthur-vyncke-homeworld-collapse.mp3",
  },
  {
    songId: 2,
    title: "Sunset Drive",
    artist: "Tokyo Music Walker",
    image: "https://www.free-stock-music.com/thumbnails/tokyo-music-walker-sunset-drive.jpg",
    path: "https://www.free-stock-music.com/music/tokyo-music-walker-sunset-drive.mp3",
  },
  {
    songId: 3,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 4,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 5,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 6,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 7,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 8,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 9,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 10,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 11,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 12,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 13,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 14,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 15,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 16,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 17,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 18,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 19,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 20,
    title: "",
    artist: "",
    image: "",
    path: "",
  },
  {
    songId: 21,
    title: "",
    artist: "",
    image: "",
    path: "",
  }
];