export const songsDB = [
  {
    id: 1,
    title: "Homeworld Collapse",
    artist: "Arthur Vyncke",
    image: "https://www.free-stock-music.com/thumbnails/arthur-vyncke-homeworld-collapse.jpg",
    path: "https://www.free-stock-music.com/music/arthur-vyncke-homeworld-collapse.mp3",
  },
  {
    id: 2,
    title: "Sunset Drive",
    artist: "Tokyo Music Walker",
    image: "https://www.free-stock-music.com/thumbnails/tokyo-music-walker-sunset-drive.jpg",
    path: "https://www.free-stock-music.com/music/tokyo-music-walker-sunset-drive.mp3",
  },
  {
    id: 3,
    title: "Solecism",
    artist: "Scott Buckley",
    image: "https://www.free-stock-music.com/thumbnails/scott-buckley-solecism.jpg",
    path: "https://www.free-stock-music.com/music/scott-buckley-solecism.mp3",
  },
  {
    id: 4,
    title: "J a z z",
    artist: "Deoxys Beats",
    image: "https://www.free-stock-music.com/thumbnails/deoxys-beats-j-a-z-z.jpg",
    path: "https://www.free-stock-music.com/music/deoxys-beats-j-a-z-z.mp3",
  },
  {
    id: 5,
    title: "Miyazaki’s House",
    artist: "Schematist",
    image: "https://www.free-stock-music.com/thumbnails/schematist-miyazakis-house.jpg",
    path: "https://www.free-stock-music.com/music/schematist-miyazakis-house.mp3",
  },
  {
    id: 6,
    title: "Jazzaddict’s Intro",
    artist: "Cosimo Fogg (201)",
    image: "https://www.free-stock-music.com/thumbnails/cosimo-fogg-201-jazzaddicts-intro.jpg",
    path: "https://www.free-stock-music.com/music/cosimo-fogg-201-jazzaddicts-intro.mp3",
  },
  {
    id: 7,
    title: "Midnight Stroll",
    artist: "Ghostrifter Official",
    image: "https://www.free-stock-music.com/thumbnails/ghostrifter-official-midnight-stroll.jpg",
    path: "https://www.free-stock-music.com/music/ghostrifter-official-midni'gh't-stroll.mp3",
  },
  {
    id: 8,
    title: "Day Ahead",
    artist: "Joe Crotty",
    image: "https://www.free-stock-music.com/thumbnails/joe-crotty-day-ahead.jpg",
    path: "https://www.free-stock-music.com/music/joe-crotty-day-ahead.mp3",
  },
  {
    id: 9,
    title: "Apocalypse Blues",
    artist: "Alexander Nakarada",
    image: "https://www.free-stock-music.com/thumbnails/alexander-nakarada-apocalypse-blues.jpg",
    path: "https://www.free-stock-music.com/music/alexander-nakarada-apocalypse-blues.mp3",
  },
  {
    id: 10,
    title: "Falling Star",
    artist: "Purrple Cat",
    image: "https://www.free-stock-music.com/thumbnails/purrple-cat-falling-star.jpg",
    path: "https://www.free-stock-music.com/music/purrple-cat-falling-star.mp3",
  },
  {
    id: 11,
    title: "Gentle Breeze",
    artist: "Purrple Cat",
    image: "https://www.free-stock-music.com/thumbnails/purrple-cat-gentle-breeze.jpg",
    path: "https://www.free-stock-music.com/music/purrple-cat-gentle-breeze.mp3",
  },
  {
    id: 12,
    title: "Moonlit Walk",
    artist: "Purrple Cat",
    image: "https://www.free-stock-music.com/thumbnails/purrple-cat-moonlit-walk.jpg",
    path: "https://www.free-stock-music.com/music/purrple-cat-moonlit-walk.mp3",
  },
  {
    id: 13,
    title: "This Too Shall Pass",
    artist: "Scott Buckley",
    image: "https://www.free-stock-music.com/thumbnails/scott-buckley-this-too-shall-pass.jpg",
    path: "https://www.free-stock-music.com/music/scott-buckley-this-too-shall-pass.mp3",
  },
  {
    id: 14,
    title: "The Great Battle",
    artist: "Alexander Nakarada",
    image: "https://www.free-stock-music.com/thumbnails/alexander-nakarada-the-great-battle.jpg",
    path: "https://www.free-stock-music.com/music/alexander-nakarada-the-great-battle.mp3",
  },
  {
    id: 15,
    title: "Spirit Of The Dream",
    artist: "Keys of Moon",
    image: "https://www.free-stock-music.com/thumbnails/keys-of-moon-pirit-of-the-dream.jpg",
    path: "https://www.free-stock-music.com/music/keys-of-moon-pirit-of-the-dream.mp3",
  },
  {
    id: 16,
    title: "The Epic Story",
    artist: "MaxKoMusic",
    image: "https://www.free-stock-music.com/thumbnails/maxkomusic-the-epic-story.jpg",
    path: "https://www.free-stock-music.com/music/maxkomusic-the-epic-story.mp3",
  },
  {
    id: 17,
    title: "An Epic Story",
    artist: "MaxKoMusic",
    image: "https://www.free-stock-music.com/thumbnails/maxkomusic-an-epic-story.jpg",
    path: "https://www.free-stock-music.com/music/maxkomusic-an-epic-story.mp3",
  },
  {
    id: 18,
    title: "Dramatic Adventure",
    artist: "MaxKoMusic",
    image: "https://www.free-stock-music.com/thumbnails/maxkomusic-dramatic-adventure.jpg",
    path: "https://www.free-stock-music.com/music/maxkomusic-dramatic-adventure.mp3",
  },
  {
    id: 19,
    title: "White Woodlands",
    artist: "Alexander Nakarada",
    image: "https://www.free-stock-music.com/thumbnails/alexander-nakarada-white-woodlands.jpg",
    path: "https://www.free-stock-music.com/music/alexander-nakarada-white-woodlands.mp3",
  },
  {
    id: 20,
    title: "Superepic",
    artist: "Alexander Nakarada",
    image: "https://www.free-stock-music.com/thumbnails/alexander-nakarada-superepic.jpg",
    path: "https://www.free-stock-music.com/music/alexander-nakarada-superepic.mp3",
  },
  {
    id: 21,
    title: "Pandemia",
    artist: "MaxKoMusic",
    image: "https://www.free-stock-music.com/thumbnails/maxkomusic-pandemia.jpg",
    path: "https://www.free-stock-music.com/music/maxkomusic-pandemia.mp3",
  }
];