export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const TOGGLE_RANDOM = 'TOGGLE_RANDOM';
export const TOGGLE_REPEAT = 'TOGGLE_OPTIONS';
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING';
export const IS_LOGGED = 'IS_LOGGED';
export const LOG_OUT = 'LOG_OUT';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
